# Generated by Django 4.0.5 on 2022-08-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.TextField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
